### ISSUE TITLE
Qredshift 1.7.2 stopped working after update

### ISSUE THREAD

**Issue by vilqvilq** [raphaelquintao/QRedshiftCinnamon#49]
applet disappeared form panel
restart reinstall doesn't help

mint 19.3 // cinnamon 4.4.8 // kernel 4.15.0-192-generic

**Comment by wavesurf432** [comment]
Hey, I've experienced the same issue aswell. 

I'm on Linux Mint 19.3 (Cinnamon 4.4.8), kernel 4.15.0-192-generic.

It first appeared with the second last update, but was fixable by uninstalling, then reinstalling QRedshift. The latest update (Italian Translations) has caused the applet to stop working again, but this time reinstalling doesn't fix the issue. Currently QRedshift is not appearing in bottom right of the panel, is no longer working, and isn't able to be configured since clicking the gears icon in Applets (manage) doesn't do anything.

Hope this helps!

**Comment by raphaelquintao** [comment]
I will take a look at this as soon as possible.

Thanks for report...

**Comment by wavesurf432** [comment]
Hey, hope things are good - was just curious if there's any progress on QRedshift working with Mint 19.3? I know there's only 2 months left till end of life for 19.3, so if it's not a priority, completely understand. It's working with 21.x (can't remember exact version) no problem.

Thanks again for the great applet.
